class String
	@@cmrs=""
	def obtplb
		self.to_s.scan(/./).each do |morse|
		morse(morse)
		end
		@@cmrs
	end
	def plbrs(morse)
			case morse
				when ".-"
					@@cmrs+="a"
			    when "-..."
				    @@cmrs+= "b"
			    when "-.-."
				    @@cmrs+="c" 
				when "-.."
				    @@cmrs+= "d"
				when "."
					@@cmrs+= "e"
				when "..-."
					@@cmrs+="f"
				when "--."
					@@cmrs+="g"
				when "...."
					@@cmrs+= "h"
				when ".."
					@@cmrs+= "i"
				when ".---"
					@@cmrs+="j"
				when "-.-"
					@@cmrs+="k"
				when ".-.."
					@@cmrs+="l"
				when "--"
					@@cmrs+="m"
				when "-."
					@@cmrs+="n"
				when "---"
					@@cmrs+="o"
				when ".--."
					@@cmrs+="p"
				when "--.-"
					@@cmrs+="q"
				when ".-."
					@@cmrs+="r"
				when "..."
					@@cmrs+="s"
				when "-"
					@@cmrs+="t"
				when "..-"
					@@cmrs+="u"
				when "...-"
					@@cmrs+="v"
				when ".--"
					@@cmrs+="w"
				when "-..-"
					@@cmrs+="x"
				when "-.--"
					@@cmrs+="y"
				when "--.."
					@@cmrs+="z"
				when "--.."
					@@cmrs+="1"
				when "--.."
					@@cmrs+="2"
				when "--.."
					@@cmrs+="3"
				when "--.."
					@@cmrs+="4"
				when "--.."
					@@cmrs+="5"
				when "--.."
					@@cmrs+="6"
				when "--.."
					@@cmrs+="7"
				when "--.."
					@@cmrs+="8"
				when "--.."
					@@cmrs+="9"
				when "--.."
					@@cmrs+="0"
				else
					@@cmrs="codigo morse no encontrada"
			end
	    end