puts "Digite codigo morse a convertir"
    morse = gets.chomp
	chars = morse.split
	@rsp=""
		chars.each do |char|
			case char
				when ".-"
					@rsp+="a"
			    when "-..."
				    @rsp+= "b"
			    when "-.-."
				    @rsp+="c" 
				when "-.."
				    @rsp+= "d"
				when "."
					@rsp+= "e"
				when "..-."
					@rsp+="f"
				when "--."
					@rsp+="g"
				when "...."
					@rsp+= "h"
				when ".."
					@rsp+= "i"
				when ".---"
					@rsp+="j"
				when "-.-"
					@rsp+="k"
				when ".-.."
					@rsp+="l"
				when "--"
					@rsp+="m"
				when "-."
					@rsp+="n"
				when "---"
					@rsp+="o"
				when ".--."
					@rsp+="p"
				when "--.-"
					@rsp+="q"
				when ".-."
					@rsp+="r"
				when "..."
					@rsp+="s"
				when "-"
					@rsp+="t"
				when "..-"
					@rsp+="u"
				when "...-"
					@rsp+="v"
				when ".--"
					@rsp+="w"
				when "-..-"
					@rsp+="x"
				when "-.--"
					@rsp+="y"
				when "--.."
					@rsp+="z"
				when "--.."
					@rsp+="1"
				when "--.."
					@rsp+="2"
				when "--.."
					@rsp+="3"
				when "--.."
					@rsp+="4"
				when "--.."
					@rsp+="5"
				when "--.."
					@rsp+="6"
				when "--.."
					@rsp+="7"
				when "--.."
					@rsp+="8"
				when "--.."
					@rsp+="9"
				when "--.."
					@rsp+="0"
				else
					@rsp="codigo morse no encontrada"
			end
	    end
puts instance_eval { @rsp }