puts "Digite texto a convertir"
    text = gets.chomp.to_s
	chars = text.scan(/./)
	@rsp=""
		chars.each do |char|
			case char.to_s.downcase
				when "a"
					@rsp+=".- "
			    when "b"
				    @rsp+= "-... "
			    when "c"
				    @rsp+="-.-. " 
				when "d"
				    @rsp+= "-.. "
				when "e"
					@rsp+= ". "
				when "f"
					@rsp+="..-. "
				when "g"
					@rsp+="--. "
				when "h"
					@rsp+= ".... "
				when "i"
					@rsp+= ".. "
				when "j"
					@rsp+=".--- "
				when "k"
					@rsp+="-.- "
				when "l"
					@rsp+=".-.. "
				when "m"
					@rsp+="-- "
				when "n"
					@rsp+="-. "
				when "o"
					@rsp+="--- "
				when "p"
					@rsp+=".--. "
				when "q"
					@rsp+="--.- "
				when "r"
					@rsp+=".-. "
				when "s"
					@rsp+="... "
				when "t"
					@rsp+="- "
				when "u"
					@rsp+="..- "
				when "v"
					@rsp+="...- "
				when "w"
					@rsp+=".-- "
				when "x"
					@rsp+="-..- "
				when "y"
					@rsp+="-.-- "
				when "z"
					@rsp+="--.. "
				when "1"
					@rsp+=".---- "
				when "2"
					@rsp+="..--- "
				when "3"
					@rsp+="...-- "
				when "4"
					@rsp+="....- "
				when "5"
					@rsp+="..... "
				when "6"
					@rsp+="-.... "
				when "7"
					@rsp+="--... "
				when "8"
					@rsp+="---.. "
				when "9"
					@rsp+="----. "
				when "0"
					@rsp+="----- "
				else
					@rsp="Letra no encontrada"
			end
	    end
puts instance_eval { @rsp }