class String
	@@cmrs=""
	def obtmrs
		self.to_s.scan(/./).each do |word|
		morse(word)
		end
		@@cmrs
	end
	def morse(word)
		case word
			when "a"
				@@cmrs+=".- "
			when "b"
				@@cmrs+= "-... "
			when "c"
				@@cmrs+="-.-. " 
			when "d"
				@@cmrs+= "-.. "
			when "e"
				@@cmrs+= ". "
			when "f"
				@@cmrs+="..-. "
			when "g"
				@@cmrs+="--. "
			when "h"
				@@cmrs+= ".... "
			when "i"
				@@cmrs+= ".. "
			when "j"
				@@cmrs+=".--- "
			when "k"
				@@cmrs+="-.- "
			when "l"
				@@cmrs+=".-.. "
			when "m"
				@@cmrs+="-- "
			when "n"
				@@cmrs+="-. "
			when "o"
				@@cmrs+="--- "
			when "p"
				@@cmrs+=".--. "
			when "q"
				@@cmrs+="--.- "
			when "r"
				@@cmrs+=".-. "
			when "s"
				@@cmrs+="... "
			when "t"
				@@cmrs+="- "
			when "u"
				@@cmrs+="..- "
			when "v"
				@@cmrs+="...- "
			when "w"
				@@cmrs+=".-- "
			when "x"
				@@cmrs+="-..- "
			when "y"
				@@cmrs+="-.-- "
			when "z"
				@@cmrs+="--.. "
			when "1"
				@@cmrs+=".---- "
			when "2"
				@@cmrs+="..--- "
			when "3"
				@@cmrs+="...-- "
			when "4"
				@@cmrs+="....- "
			when "5"
				@@cmrs+="..... "
			when "6"
				@@cmrs+="-.... "
			when "7"
				@@cmrs+="--... "
			when "8"
				@@cmrs+="---.. "
			when "9"
				@@cmrs+="----. "
			when "0"
				@@cmrs+="----- "
			else
				@@cmrs="Letra no encontrada"
		end
	end
end